version: '3.8'

services:
  # 1. –¢–≤–æ–π –ë–æ—Ç
#  bot:
#    build: .
#    container_name: babykea_bot
#    restart: always
#    ports:
#      - "8000:8000"
#    # –ö–æ–º–∞–Ω–¥–∞ –∑–∞–ø—É—Å–∫–∞: —Å–ø–µ—Ä–≤–∞ –Ω–∞–∫–∞—Ç—ã–≤–∞–µ–º –º–∏–≥—Ä–∞—Ü–∏–∏, –ø–æ—Ç–æ–º –∑–∞–ø—É—Å–∫–∞–µ–º –±–æ—Ç–∞
#    command: sh -c "alembic upgrade head && python -m app.main"
#    env_file:
#      - .env
#    environment:
#      # –í–Ω—É—Ç—Ä–∏ –¥–æ–∫–µ—Ä–∞ —Ö–æ—Å—Ç—ã –Ω–∞–∑—ã–≤–∞—é—Ç—Å—è –∏–º–µ–Ω–∞–º–∏ —Å–µ—Ä–≤–∏—Å–æ–≤
#      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    volumes:
#      # –ü—Ä–æ–±—Ä–∞—Å—ã–≤–∞–µ–º –º–µ–¥–∏–∞, —á—Ç–æ–±—ã –±–æ—Ç –º–æ–≥ —Å–æ—Ö—Ä–∞–Ω—è—Ç—å/—á–∏—Ç–∞—Ç—å —Ñ–∞–π–ª—ã
#      - ./app/mediafile_for_bot:/app/app/mediafile_for_bot
#      # –ü—Ä–æ–±—Ä–∞—Å—ã–≤–∞–µ–º ChromaDB (–≤–µ–∫—Ç–æ—Ä–Ω–æ–µ —Ö—Ä–∞–Ω–∏–ª–∏—â–µ), —á—Ç–æ–±—ã –Ω–µ –ø–æ—Ç–µ—Ä—è—Ç—å –±–∞–∑—É –ø—Ä–∏ —Ä–µ—Å—Ç–∞—Ä—Ç–µ
#      - ./app/chromadb_storage:/app/app/chromadb_storage
#    depends_on:
#      - db
#      - redis
#    networks:
#      - bot_net

#  # 2. –ë–∞–∑–∞ –¥–∞–Ω–Ω—ã—Ö PostgreSQL
#  db:
#    image: postgres:15-alpine
#    container_name: babykea_postgres
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432" # –û—Å—Ç–∞–≤–ª—è–µ–º –ø–æ—Ä—Ç –æ—Ç–∫—Ä—ã—Ç—ã–º, —á—Ç–æ–±—ã —Ç—ã –º–æ–≥ –ø–æ–¥–∫–ª—é—á–∏—Ç—å—Å—è –∫ –ë–î —á–µ—Ä–µ–∑ DBeaver/PgAdmin
#    networks:
#      - bot_net

  # 3. Redis (–ö—ç—à –∏ FSM)
  redis:
    image: redis:7.2-alpine
    container_name: babykea_redis
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
      --save 60 1
      --appendonly yes
      --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379" # –û—Ç–∫—Ä—ã–≤–∞–µ–º –ø–æ—Ä—Ç –¥–ª—è –æ—Ç–ª–∞–¥–∫–∏ —Å –ª–æ–∫–∞–ª–∫–∏
    networks:
      - bot_net

volumes:
  postgres_data:
  redis_data:

networks:
  bot_net:
    driver: bridge


#redis:
#    image: redis:alpine
#    command: redis-server --appendonly yes  # üëà –í–∫–ª—é—á–∞–µ—Ç —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∏–µ –Ω–∞ –¥–∏—Å–∫
#    volumes:
#      - redis_data:/data