version: '3.8'

services:
  # 1. Telegram-бот + веб-сервер (webhook + лендинг)
  bot_telegram:
    build: .
    container_name: babykea_telegram
    restart: always
    ports:
      - "8000:8000"
    command: python run_telegram.py
    env_file:
      - .env
    environment:
      - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app/mediafile_for_bot:/app/app/mediafile_for_bot
      - ./chromadb_storage:/app/chromadb_storage
    depends_on:
      - db
      - redis
    networks:
      - bot_net

  # 2. VK-бот (будет активирован позже)
  # bot_vk:
  #   build: .
  #   container_name: babykea_vk
  #   restart: always
  #   command: python run_vk.py
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   volumes:
  #     - ./chromadb_storage:/app/chromadb_storage
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - bot_net

  # 3. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: babykea_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot_net

  # 4. Redis (Кэш и FSM)
  redis:
    image: redis:7.2-alpine
    container_name: babykea_redis
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
      --save 60 1
      --appendonly yes
      --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - bot_net

  # 5. Metabase (Аналитика)
  metabase:
    image: metabase/metabase:latest
    container_name: babykea_metabase
    restart: always
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - bot_net

volumes:
  postgres_data:
  redis_data:
  metabase_data:

networks:
  bot_net:
    driver: bridge